export const products = [
  {
    id: 'prod-netflix',
    slug: 'netflix-premium',
    name: 'Netflix Premium',
    category: 'Streaming',
    badge: 'Instant delivery',
    description: 'Premium streaming access for one account with secure setup guidance.',
    variants: [
      { id: 'v1', name: '1 Month', price: 12.99, stockType: 'digital' },
      { id: 'v2', name: '3 Months', price: 31.99, stockType: 'digital' },
      { id: 'v3', name: '1 Year', price: 119.99, stockType: 'digital' },
    ],
    inputRequirements: ['email'],
  },
  {
    id: 'prod-capcut',
    slug: 'capcut-pro',
    name: 'CapCut Pro',
    category: 'Productivity',
    badge: 'Trending',
    description: 'Unlock premium templates and advanced editing tools for creators and teams.',
    variants: [
      { id: 'v4', name: '1 Month', price: 8.99, stockType: 'digital' },
      { id: 'v5', name: '12 Months', price: 69.99, stockType: 'digital' },
    ],
    inputRequirements: ['email'],
  },
  {
    id: 'prod-spotify',
    slug: 'spotify-premium',
    name: 'Spotify Premium',
    category: 'Streaming',
    badge: 'Popular',
    description: 'Music streaming with premium ad-free playback and offline downloads.',
    variants: [
      { id: 'v6', name: '1 Month', price: 6.99, stockType: 'digital' },
      { id: 'v7', name: '3 Months', price: 18.99, stockType: 'digital' },
    ],
    inputRequirements: ['email'],
  },
  {
    id: 'prod-topup',
    slug: 'mobile-topup',
    name: 'Mobile Recharge',
    category: 'Telecom',
    badge: 'Instant',
    description: 'Recharge prepaid balances for local and international operators.',
    variants: [
      { id: 'v8', name: 'Top-up 10', price: 10.0, stockType: 'physical' },
      { id: 'v9', name: 'Top-up 25', price: 25.0, stockType: 'physical' },
      { id: 'v10', name: 'Top-up 50', price: 50.0, stockType: 'physical' },
    ],
    inputRequirements: ['phone', 'operator'],
  },
  {
    id: 'prod-snapchat',
    slug: 'snapchat-plus',
    name: 'Snapchat+ Premium',
    category: 'Social',
    badge: 'Best value',
    description: 'Secure access to premium social features and advanced customization tools.',
    variants: [
      { id: 'v11', name: '1 Month', price: 8.49, stockType: 'digital' },
      { id: 'v12', name: '6 Months', price: 42.99, stockType: 'digital' },
    ],
    inputRequirements: ['username'],
  },
  {
    id: 'prod-giftcard',
    slug: 'steam-gift-card',
    name: 'Steam Gift Card',
    category: 'Gaming',
    badge: 'Top seller',
    description: 'Redeemable digital gift cards for gaming and digital purchases.',
    variants: [
      { id: 'v13', name: '5 USD', price: 5.0, stockType: 'digital' },
      { id: 'v14', name: '20 USD', price: 20.0, stockType: 'digital' },
      { id: 'v15', name: '50 USD', price: 50.0, stockType: 'digital' },
    ],
    inputRequirements: ['email'],
  },
] as const;
